### ISSUE TITLE
Beyond mapping single triples

### ISSUE THREAD

**Issue by midorna** [kg-construct/yarrrml-spec#11]
When sub-graphs for objects shall be generated using the current YARRRML specification, we need to define multiple triples with non-blank subject nodes as references, even when these are not required further. Therefore, a shortcut notation is proposed, which can be used to reduce the number of mappings to be specified.  
Note: The following proposal adds to the [proposal](https://github.com/kg-construct/yarrrml-spec/issues/8#issuecomment-2454675506) for issue https://github.com/kg-construct/yarrrml-spec/issues/8. It uses and extends the functional notation shortcut suggested there.

**Proposal**
Use `spom(<subject>, <predicate-objects> )` as a template for subject-predicate-object mappings, which enables the creation of graphs using embedded templates.  
If `<subject>`'s IRI is not required, a blank node can be used, which is indicated by an underscore (`_`).  
If used for "simple" mappings, a new field `spo` would be required.

**Example 1: current syntax**

The following example is just for introducing the notation. 

```
mappings:
  person:
    s: $(person)
    po:
      - [foaf:firstName, $(firstname)]
      - [foaf:lastName, $(lastname)]
```

**Example 1: proposed syntax**

```
mappings:
  person:
    spo: spom($(person), 
              [pom(foaf:firstName, $(firstname)), 
               pom(foaf:lastName, $(lastname))])
```

**Example 2: current syntax**

Now, we map values of bounding box objects, which have a height, a length and a width, each defined as own objects.

```
mappings
  BoundingBox:
    s: ex:BoundingBox-$(Id)
    po:
      - [a, my:BoundingBox]
      - [my:hasHeight, ex:BoxHeight-$(Height)~iri]
      - [my:hasLength, ex:BoxLength-$(Length)~iri]
      - [my:hasWidth, ex:BoxWidth-$(Width)~iri]

  BoxHeight:
    s: ex:BoxHeight-$(Height)
    po: [[my:hasValue, $(Height), xsd:float]]

  BoxLength:
    s: ex:BoxLength-$(Length)
    po: [[my:hasValue, $(Length), xsd:float]]

  BoxWidth:
      s: ex:BoxWidth-$(Width)
      po: [[my:hasValue, $(Width), xsd:float]]
```

*Remarks*  
The objects of all three dimensions are defined as subclasses of `qudt:QuantityValue`. 
I.e. they all have a value and a unit. In the shown example, the unit is always the same and not further specified in the mappings.
In fact, the unit is defined in a subclass of `quantitykind:Length` in a used ontology, and this class is declared to be the range of all 3 dimension properties of our bounding box. If units differ from a data source, the respective unit should also be part of the mapping, of course.

**Example 2: proposed syntax**

```
mappings
  BoundingBox:
    s: ex:BoundingBox-$(Id)
    po: 
      - pom(a, my:BoundingBox)
      - pom(my:hasHeight, spom(_, pom(my:hasValue, $(Height), xsd:float)))
      - pom(my:hasLength, spom(_, pom(my:hasValue, $(Length), xsd:float)))
      - pom(my:hasWidth, spom(_, pom(my:hasValue, $(Width), xsd:float)))
```

**Comment by bjdmeest** [comment]
Where I do understand an interest in nested mappings, I keep my same reservations as just mentioned in https://github.com/kg-construct/yarrrml-spec/issues/8 (i.e. not adding too much functionality outside of YAML).

Would something like below be reasonable for you?

```yaml
mappings
  BoundingBox:
    s: ex:BoundingBox-$(Id)
    po: 
      - [a, my:BoundingBox]
      - p: my:hasHeight
        o:
          po: [my:hasValue, $(Height), xsd:float]
      - p: my:hasLength
        o: 
          po: [my:hasValue, $(Length), xsd:float]
      - p: my:hasWidth
        o:
          po: [my:hasValue, $(Width), xsd:float]
```
