### ISSUE TITLE
Add option to use `graph` as keyword instead of `graphs`

### ISSUE THREAD

**Issue by x-m-el** [kg-construct/yarrrml-spec#9]
For the yarrrml spec, it might be okay to use `graph` instead of `graphs` as a keyword, more info about this discussion at https://github.com/oeg-upm/yatter/issues/78

E.g. the following should be correct, following the spec (currently the spec only mentions `graphs`)
```
mappings:
  test:
    graph: https://example.com/$(id)
    s: https://example.com/$(id)
    po:
      - [a, ext:Test]
```
